### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by thatismyfeet** [upgradeQ/Obscounter#1]
Please add a function/setting to set the initial/starting value of the count. I am starting at 4184

**Comment by upgradeQ** [comment]
You might change this line https://github.com/upgradeQ/Obscounter/blob/0b22fe1c3bb1081488545c075535d96e227463d8/hotkey_counter.py#L8
 to your liking. Current version deserves a major refactor to make next changes easier to add, so for now to start from number you must change code.
